package models.generator.graphQlSchema

import bml.util.gql.GraphQLUtil
import lib.Constants

class GraphQlSchemaComments(version: String, userAgent: Option[String]) {


  private val elements = Seq(
    Some(s"Generated by BML-Generators for API Builder - ${Constants.ApibuilderUrl}"),
    Some(s"Service version: $version"),
    userAgent
  ).flatten

  val forClassFile: String = GraphQLUtil.textToComment(elements)
}
